BlockPlayerJoin: false
BlockPlayerQuit: false
HandleAFK: false
AutoAFK: 0

LocalChat: false
GlobalRange: 0
WorldRanges:
  testWorld: 10

Worlds:
  testWorld: TW

AnnounceFactionModeOnJoin: true
DefaultFactionMode: global
FactionModes:
  geNAZt: faction
