name: CloudChatBukkit
author: geNAZt
main: net.cubespace.CloudChatBukkit.CloudChatBukkitPlugin
version: ${version}
depend: [Yamler]
softdepend: [Multiverse-Core, Vault, BungeePermsBukkit, Factions, Towny]
commands:
    fchat:
        description: Toggle Factionchat mode
        aliases: [fc]
        permission: cloudchat.factions.command.fchat
        permission-message: You do not have permission to this Command
        usage: /<command> *([a|at|e|f|g|t])
    tchat:
        description: Write into your Towns Chat
        aliases: [tc]
        permission: cloudchat.towny.command.tchat
        permission-message: You do not have permission to this Command
        usage: /<command> [message]
    nchat:
        description: Write into your Towns Nation Chat
        aliases: [nc]
        permission: cloudchat.towny.command.nchat
        permission-message: You do not have permission to this Command
        usage: /<command> [message]
    log:
        description: Toggle Log mode
        permission: cloudchat.command.log
        permission-message: You do not have permission to this Command
        usage: /<command>
    afk:
        description: Toggle AFK mode
        permission: cloudchat.command.afk
        permission-message: You do not have permission to this Command
        usage: /<command>
    'ccb:reload':
        description: Reload the config on this node
        permission: cloudchat.command.ccb.reload
        permission-message: You do not have permission to this Command
        usage: /<command>
permissions:
    cloudchat.towny.command.nchat:
        description: Gives access to the Towns Nation Chat
    cloudchat.towny.command.tchat:
        description: Gives access to the Towns Chat
    cloudchat.factions.command.fchat:
        description: Gives access to the Chat mode switcher
    cloudchat.command.log:
        description: Gives access to /log which relays the Log into the Chat (from the current server)